### ISSUE TITLE
Report File Name and Line Number for all MDL Errors

### ISSUE THREAD

**Issue by cnlbob** [mcellteam/mcell#17]
MCell should report the MDL file name and line number for all errors and warnings.

I'll update this with examples as they're discovered, but it would be good to ensure that this is done systematically so it's not handled on a case by case basis ... if possible.

**Comment by jczech** [comment]
I'm marking this as fixed since a lot of work has been done on addressing this recently. If any cases have been missed, we can address them as they come up.
